spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rplace?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ${DB_PASSWORD:example}
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: filesystem:../../database/migration

# 로그 레벨 기본 설정
logging:
  level:
    org.flywaydb: info
